"""init neo-parse schema

Revision ID: a266b2b5cf28
Revises: 
Create Date: 2026-06-28 22:10:56.405625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a266b2b5cf28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.Enum('INVOICE', 'CONTRACT', 'RECEIPT', 'REPORT', 'OTHER', name='document_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('ix_documents_doc_type', 'documents', ['doc_type'], unique=False)
    op.create_table('schemas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parse_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('schema_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='parse_job_status'), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('markdown_output', sa.Text(), nullable=True),
    sa.Column('json_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parse_jobs_created_at', 'parse_jobs', ['created_at'], unique=False)
    op.create_index('ix_parse_jobs_document_id', 'parse_jobs', ['document_id'], unique=False)
    op.create_index('ix_parse_jobs_status', 'parse_jobs', ['status'], unique=False)
    op.create_table('parse_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('rect_top', sa.Float(), nullable=False),
    sa.Column('rect_left', sa.Float(), nullable=False),
    sa.Column('rect_width', sa.Float(), nullable=False),
    sa.Column('rect_height', sa.Float(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('json_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['parse_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parse_sections_job_id', 'parse_sections', ['job_id'], unique=False)
    op.create_index('ix_parse_sections_job_page', 'parse_sections', ['job_id', 'page_number'], unique=False)
    op.create_index('ix_parse_sections_label', 'parse_sections', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parse_sections_label', table_name='parse_sections')
    op.drop_index('ix_parse_sections_job_page', table_name='parse_sections')
    op.drop_index('ix_parse_sections_job_id', table_name='parse_sections')
    op.drop_table('parse_sections')
    op.drop_index('ix_parse_jobs_status', table_name='parse_jobs')
    op.drop_index('ix_parse_jobs_document_id', table_name='parse_jobs')
    op.drop_index('ix_parse_jobs_created_at', table_name='parse_jobs')
    op.drop_table('parse_jobs')
    op.drop_table('schemas')
    op.drop_index('ix_documents_doc_type', table_name='documents')
    op.drop_index('ix_documents_created_at', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
